// Frei erfundene Lokale für die öffentliche Startseite. Die echten Entwürfe
// liegen zwar auch im Netz, aber unverlinkt und unter einer Adresse mit
// Kennung – erreichbar nur über den QR-Code oder Link, den du herausgibst.
//
// Bewusst ohne Telefonnummer: eine ausgedachte Nummer könnte bei einem
// echten Anschluss klingeln. Die Straße ist als Musteradresse erkennbar.

export const DEMO_LEADS = [
  {
    placeId: "demo-wirtshaus",
    kueche: "bayerisch",
    name: "Wirtshaus zur Alten Linde",
    ort: "Mühldorf am Inn",
    adresse: "Musterstraße 1, 84453 Mühldorf am Inn",
    rating: 4.7,
    anzahlBewertungen: 428,
  },
  {
    placeId: "demo-trattoria",
    kueche: "italienisch",
    name: "Trattoria Bella Vista",
    ort: "Altötting",
    adresse: "Musterplatz 4, 84503 Altötting",
    rating: 4.6,
    anzahlBewertungen: 312,
  },
  {
    placeId: "demo-sakura",
    kueche: "japanisch",
    name: "Sakura Sushi & Ramen",
    ort: "Mühldorf am Inn",
    adresse: "Musterstraße 18, 84453 Mühldorf am Inn",
    rating: 4.8,
    anzahlBewertungen: 596,
  },
  {
    placeId: "demo-jadegarten",
    kueche: "chinesisch",
    name: "Jadegarten",
    ort: "Altötting",
    adresse: "Musterstraße 5, 84503 Altötting",
    rating: 4.5,
    anzahlBewertungen: 233,
  },
  {
    placeId: "demo-baannam",
    kueche: "thailaendisch",
    name: "Baan Nam Thai",
    ort: "Mühldorf am Inn",
    adresse: "Musterweg 12, 84453 Mühldorf am Inn",
    rating: 4.7,
    anzahlBewertungen: 201,
  },
  {
    placeId: "demo-sonnenblume",
    kueche: "vietnamesisch",
    name: "Hoa Mai Vietnamesische Küche",
    ort: "Altötting",
    adresse: "Musterplatz 19, 84503 Altötting",
    rating: 4.8,
    anzahlBewertungen: 164,
  },
  {
    placeId: "demo-tandoor",
    kueche: "indisch",
    name: "Tandoor Haus",
    ort: "Tüßling",
    adresse: "Musterstraße 8, 84577 Tüßling",
    rating: 4.6,
    anzahlBewertungen: 187,
  },
  {
    placeId: "demo-damaskus",
    kueche: "syrisch",
    name: "Beit Damaskus",
    ort: "Kraiburg am Inn",
    adresse: "Musterweg 3, 84559 Kraiburg am Inn",
    rating: 4.7,
    anzahlBewertungen: 129,
  },
  {
    placeId: "demo-meltemi",
    kueche: "griechisch",
    name: "Taverna Meltemi",
    ort: "Kraiburg am Inn",
    adresse: "Musterweg 7, 84559 Kraiburg am Inn",
    rating: 4.5,
    anzahlBewertungen: 274,
  },
  {
    placeId: "demo-anatolia",
    kueche: "tuerkisch",
    name: "Anatolia Grillhaus",
    ort: "Tüßling",
    adresse: "Musterstraße 23, 84577 Tüßling",
    rating: 4.6,
    anzahlBewertungen: 188,
  },
  {
    placeId: "demo-morgenrot",
    kueche: "cafe",
    name: "Café Morgenrot",
    ort: "Altötting",
    adresse: "Musterplatz 11, 84503 Altötting",
    rating: 4.9,
    anzahlBewertungen: 341,
  },
  {
    placeId: "demo-losteria",
    kueche: "italienisch",
    name: "Losteria",
    ort: "München",
    adresse: "Musterstraße 45, 80331 München",
    rating: 4.7,
    anzahlBewertungen: 892,
  },
  {
    placeId: "demo-hans-im-glück",
    kueche: "bayerisch",
    name: "Hans im Glück",
    ort: "München",
    adresse: "Musterallee 22, 80331 München",
    rating: 4.6,
    anzahlBewertungen: 1247,
  },
];
